twig:
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
        globals:
        knp_paginator_template: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
